import G from '../tools/glossary.js';

export const responseModel = ['min', 'full'] as const;

export type ViewMode = (typeof responseModel)[number];

export const responseValue = {
  MINIMAL: 'min',
  FULL: 'full',
} as const;

export const responseStructure = {
  ID: 'id',
  GUID: 'guid',
  CODE: 'code',
  NAME_EN: 'name_en',
  NAME_LOCAL: 'name_local',
  DEFAULT_CURRENCY_CODE: 'default_currency_code',
  DEFAULT_LANGUAGE_CODE: 'default_language_code',
  IS_ACTIVE: 'is_active',
  ACTIVE: 'active',
  TIMEZONE_DEFAULT: 'timezone_default',
  PHONE_PREFIX: 'phone_prefix',

  NAME: 'name',
  SYMBOL: 'symbol',
  DECIMAL_PLACES: 'decimal_places',

  CURRENCY: 'currency',
  FROM_CURRENCY_CODE: 'from_currency_code',
  TO_CURRENCY_CODE: 'to_currency_code',
  EXCHANGE_RATE: 'exchange_rate',
  IS_CURRENT: 'is_current',
  CREATED_BY: 'created_by',

  COUNTRY_CODE: 'country_code',
  TAX_TYPE: 'tax_type',
  TAX_NAME: 'tax_name',
  TAX_RATE: 'tax_rate',
  APPLIES_TO: 'applies_to',
  REQUIRED_TAX_NUMBER: 'required_tax_number',
  EFFECTIVE_DATE: 'effective_date',
  EXPIRY_DATE: 'expiry_date',

  KEY: 'key',
  PRIMARY_CURRENCY_CODE: 'primary_currency_code',
  PREFERRED_LANGUAGE_CODE: 'preferred_language_code',
  TIMEZONE: 'timezone',
  TAX_NUMBER: 'tax_number',
  TAX_EXEMPT: 'tax_exempt',
  BILLING_EMAIL: 'billing_email',
  BILLING_ADDRESS: 'billing_address',
  BILLING_PHONE: 'billing_phone',
  STATUS: 'status',
  SUBDOMAIN: 'subdomain',
  DATABASE_NAME: 'database_name',
  DATABASE_USERNAME: 'database_username',
  SHORT_NAME: 'short_name',
  REGISTRATION_NUMBER: 'registration_number',
  EMPLOYEE_COUNT: 'employee_count',

  TENANT: 'tenant',
  LICENSE_TYPE: 'license_type',
  BILLING_CYCLE_MONTHS: 'billing_cycle_months',
  BASE_PRICE_USD: 'base_price_usd',
  MINIMUM_SEATS: 'minimum_seats',
  CURRENT_PERIOD_START: 'current_period_start',
  CURRENT_PERIOD_END: 'current_period_end',
  NEXT_RENEWAL_DATE: 'next_renewal_date',
  TOTAL_SEATS_PURCHASED: 'total_seats_purchased',
  LICENSE_STATUS: 'license_status',

  GLOBAL_LICENSE: 'global_license',

  PORTABLE: 'portable',
  REFERENCE: 'reference',
  TRANSLATION: 'transcription',
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',

  EMPLOYEE: 'employee',
  EMPLOYEE_CODE: 'employee_code',
  ACTIVATION_DATE: 'activation_date',
  DEACTIVATION_DATE: 'deactivation_date',
  LAST_ACTIVITY_DATE: 'last_activity_date',
  CONTRACTUAL_STATUS: 'contractual_status',
  DECLARED_LONG_LEAVE: 'declared_long_leave',
  LONG_LEAVE_DECLARED_BY: 'long_leave_declared_by',
  LONG_LEAVE_DECLARED_AT: 'long_leave_declared_at',
  LONG_LEAVE_TYPE: 'long_leave_type',
  LONG_LEAVE_REASON: 'long_leave_reason',
  COMPUTED_BILLING_STATUS: 'computed_billing_status',
  GRACE_PERIOD_START: 'grace_period_start',
  GRACE_PERIOD_END: 'grace_period_end',

  PERIOD_START: 'period_start',
  PERIOD_END: 'period_end',
  BASE_EMPLOYEE_COUNT: 'base_employee_count',
  FINAL_EMPLOYEE_COUNT: 'final_employee_count',
  BASE_AMOUNT_USD: 'base_amount_usd',
  ADJUSTMENTS_AMOUNT_USD: 'adjustments_amount_usd',
  SUBTOTAL_USD: 'subtotal_usd',
  TAX_AMOUNT_USD: 'tax_amount_usd',
  TOTAL_AMOUNT_USD: 'total_amount_usd',
  BILLING_CURRENCY_CODE: 'billing_currency_code',
  EXCHANGE_RATE_USED: 'exchange_rate_used',
  BASE_AMOUNT_LOCAL: 'base_amount_local',
  ADJUSTMENTS_AMOUNT_LOCAL: 'adjustments_amount_local',
  SUBTOTAL_LOCAL: 'subtotal_local',
  TAX_AMOUNT_LOCAL: 'tax_amount_local',
  TOTAL_AMOUNT_LOCAL: 'total_amount_local',
  TAX_RULES_APPLIED: 'tax_rules_applied',
  BILLING_STATUS: 'billing_status',
  INVOICE_GENERATED_AT: 'invoice_generated_at',
  PAYMENT_DUE_DATE: 'payment_due_date',
  PAYMENT_COMPLETED_AT: 'payment_completed_at',

  METHOD_TYPE: 'method_type',
  SUPPORTED_CURRENCIES: 'supported_currencies',
  PROCESSING_FEE_RATE: 'processing_fee_rate',
  MIN_AMOUNT_USD: 'min_amount_usd',
  MAX_AMOUNT_USD: 'max_amount_usd',
  BILLING_CYCLE: 'billing_cycle',
  ADJUSTMENT: 'adjustment',
  AMOUNT_USD: 'amount_usd',
  AMOUNT_LOCAL: 'amount_local',
  CURRENCY_CODE: 'currency_code',
  PAYMENT_REFERENCE: 'payment_reference',
  TRANSACTION_STATUS: 'transaction_status',
  INITIATED_AT: 'initiated_at',
  COMPLETED_AT: 'completed_at',
  FAILED_AT: 'failed_at',
  FAILURE_REASON: 'failure_reason',
  PAYMENT_METHOD: 'payment_method',

  ADJUSTMENT_DATE: 'adjustment_date',
  EMPLOYEES_ADDED_COUNT: 'employees_added_count',
  MONTHS_REMAINING: 'months_remaining',
  PRICE_PER_EMPLOYEE_USD: 'price_per_employee_usd',
  PAYMENT_STATUS: 'payment_status',
  PAYMENT_DUE_IMMEDIATELY: 'payment_due_immediately',
  INVOICE_SENT_AT: 'invoice_sent_at',

  DETECTION_TYPE: 'detection_type',
  EMPLOYEE_LICENSES_AFFECTED: 'employee_licenses_affected',
  RISK_LEVEL: 'risk_level',
  ACTION_TAKEN: 'action_taken',
  NOTES: 'notes',
  RESOLVED_AT: 'resolved_at',
  RESOLVED_BY: 'resolved_by',

  EMPLOYEE_LICENSE: 'employee_license',
  MONITORING_DATE: 'monitoring_date',
  LAST_PUNCH_DATE: 'last_punch_date',
  PUNCH_COUNT_7_DAYS: 'punch_count_7_days',
  PUNCH_COUNT_30_DAYS: 'punch_count_30_days',
  CONSECUTIVE_ABSENT_DAYS: 'consecutive_absent_days',
  STATUS_AT_DATE: 'status_at_date',
} as const;

export const tableName = {
  COUNTRY: `${G.tableConf}_country`,
  CURRENCY: `${G.tableConf}_currency`,
  EXCHANGE_RATE: `${G.tableConf}_exchange_rate`,
  LANGUAGE: `${G.tableConf}_language`,
  TAX_RULE: `${G.tableConf}_tax_rule`,
  LEXICON: `${G.tableConf}_lexicon`,
  CLIENT: `${G.tableConf}_client`,
  PROFILE: `${G.tableConf}_profile`,

  TENANT: `${G.tableAp}_tenant`,
  GLOBAL_LICENSE: `${G.tableAp}_global_license`,
  EMPLOYEE_LICENSE: `${G.tableAp}_employee_license`,
  BILLING_CYCLE: `${G.tableAp}_billing_cycle`,
  LICENSE_ADJUSTMENT: `${G.tableAp}_license_adjustment`,
  PAYMENT_METHOD: `${G.tableAp}_payment_method`,
  PAYMENT_TRANSACTION: `${G.tableAp}_payment_transaction`,
  FRAUD_DETECTION_LOG: `${G.tableAp}_fraud_detection_log`,
  ACTIVITY_MONITORING: `${G.tableAp}_activity_monitoring`,
} as const;

export const EntityRoute = {
  MASTER: 'm',
  TENANT: 't',
} as const;
