<template>
  <!-- État de chargement -->
  <div v-if="isLoading" class="flex flex-col items-center justify-center py-20 gap-3">
    <div class="w-8 h-8 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin"></div>
    <p class="text-sm text-gray-500">Chargement des mémos...</p>
  </div>

  <!-- État d'erreur -->
  <div v-else-if="error" class="flex flex-col items-center justify-center py-20 gap-3">
    <span class="text-4xl">⚠️</span>
    <p class="text-gray-600">{{ error }}</p>
    <button v-if="onRetry" @click="onRetry"
            class="px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
      Réessayer
    </button>
  </div>

  <!-- Liste ou état vide -->
  <div v-else>
    <!-- Résultat count + per-page -->
    <div class="flex items-center justify-between mb-4">
      <div class="flex items-center gap-2 text-sm text-gray-600">
        <span class="text-lg">📋</span>
        <span class="font-medium">{{ memos.length }} mémo{{ memos.length > 1 ? 's' : '' }} trouvé{{ memos.length > 1 ? 's' : '' }}</span>
      </div>
      <select
          v-model="perPage"
          class="border border-gray-200 rounded-lg px-2 py-1 text-sm text-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500"
      >
        <option :value="10">10 par page</option>
        <option :value="25">25 par page</option>
        <option :value="50">50 par page</option>
      </select>
    </div>

    <!-- État vide -->
    <div v-if="memos.length === 0" class="flex flex-col items-center justify-center py-20 gap-3">
      <div class="relative">
        <span class="text-6xl">📝</span>
        <div class="absolute inset-0 bg-blue-100 rounded-full opacity-20 scale-150"></div>
      </div>
      <h3 class="text-lg font-semibold text-gray-800">{{ emptyTitle }}</h3>
      <p class="text-sm text-gray-500 max-w-xs text-center">{{ emptyDescription }}</p>
      <slot name="empty-action" />
    </div>

    <!-- Liste des mémos -->
    <div v-else class="flex flex-col gap-2">
      <div
          v-for="memo in memosPagines"
          :key="memo.guid"
          @click="handleMemoClick(memo)"
          class="bg-white border border-gray-100 rounded-xl cursor-pointer hover:shadow-md transition-all duration-200 hover:-translate-y-px group"
      >
        <!-- Bordure gauche colorée par statut -->
        <div class="flex items-stretch">
          <div :class="['w-1 rounded-l-xl flex-shrink-0', statusBorderColor(memo.statut)]"></div>

          <div class="flex items-center gap-4 px-4 py-3.5 flex-1 min-w-0">

            <!-- Icône type -->
            <div :class="['w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 text-lg', typeIconBg(memo.type)]">
              {{ getTypeIcon(memo.type) }}
            </div>

            <!-- Titre + ID -->
            <div class="flex flex-col min-w-0 w-44 flex-shrink-0">
              <span class="text-sm font-semibold text-gray-900 truncate">{{ memo.titre }}</span>
              <span class="text-xs text-gray-400 truncate">ID: {{ memo.guid?.slice(-13) }}</span>
            </div>

            <!-- Avatar + Interlocuteur -->
            <div class="flex items-center gap-2.5 flex-1 min-w-0">
              <div class="w-8 h-8 rounded-full bg-gray-200 flex items-center justify-center flex-shrink-0 overflow-hidden">
                <span v-if="memo.autoGenerated" class="text-sm">🤖</span>
                <span v-else class="text-xs font-semibold text-gray-600">
                  {{ initials(memo.interlocuteurNom) }}
                </span>
              </div>
              <div class="flex flex-col min-w-0">
                <span class="text-sm font-medium text-gray-800 truncate">
                  {{ memo.autoGenerated ? 'System' : (memo.interlocuteurNom || '—') }}
                </span>
                <span class="text-xs text-gray-400 truncate">
                  {{ memo.interlocuteurCode || 'Auto' }} · {{ memo.interlocuteurDepartement || '' }}
                </span>
              </div>
            </div>

            <!-- Badge type -->
            <div class="hidden sm:flex flex-shrink-0">
              <span :class="['px-2.5 py-1 rounded-full text-xs font-medium', typeBadgeClass(memo.type)]">
                {{ getTypeLabel(memo.type) }}
              </span>
            </div>

            <!-- Statut -->
            <div class="flex-shrink-0">
              <span :class="['px-2.5 py-1 rounded-full text-xs font-semibold', statusBadgeClass(memo.statut)]">
                {{ getStatusLabel(memo.statut) }}
              </span>
            </div>

            <!-- Date incident -->
            <div class="hidden md:flex flex-col items-start flex-shrink-0 w-36">
              <div class="flex items-center gap-1 text-xs text-gray-500">
                <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <rect x="3" y="4" width="18" height="18" rx="2" ry="2" stroke-width="2"/>
                  <line x1="16" y1="2" x2="16" y2="6" stroke-width="2"/>
                  <line x1="8" y1="2" x2="8" y2="6" stroke-width="2"/>
                  <line x1="3" y1="10" x2="21" y2="10" stroke-width="2"/>
                </svg>
                <span>{{ formatDate(memo.dateIncident || memo.dateCreation) }}</span>
              </div>
            </div>

            <!-- Messages count -->
            <div class="flex items-center gap-1 text-gray-400 flex-shrink-0 ml-auto">
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"/>
              </svg>
              <span class="text-xs">{{ memo.messagesCount }}</span>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                   stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                   class="w-4 h-4 hover:w-5 hover:h-5 transition-all duration-500 hover:text-black"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M9 6l6 6l-6 6" />
              </svg>
            </div>

          </div>
        </div>
      </div>
    </div>

    <!-- Pagination -->
    <div v-if="totalPages > 1" class="flex items-center justify-center gap-1 mt-6">
      <button
          @click="currentPage--"
          :disabled="currentPage === 1"
          class="w-8 h-8 rounded-lg flex items-center justify-center text-black hover:bg-white disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
      >
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
        </svg>
      </button>

      <div class="flex bg-white rounded-sm overflow-hidden items-center justify-center p-1">
        <template v-for="page in paginationPages" :key="page">
          <button
              v-if="page !== '...'"
              @click="currentPage = +page"
              :class="['w-7 h-7 rounded-lg text-sm font-medium transition-colors',
            currentPage === +page ? 'bg-blue-600 text-white' : 'text-gray-600 hover:bg-gray-200']"
          >{{ page }}</button>
          <span v-else class="w-8 h-8 flex items-center justify-center text-gray-400 text-sm">...</span>
        </template>
      </div>



      <button
          @click="currentPage++"
          :disabled="currentPage === totalPages"
          class="w-8 h-8 rounded-lg flex items-center justify-center text-black hover:bg-white disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
      >
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
        </svg>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';

interface Memo {
  guid: string;
  titre: string;
  type: string;
  statut: string;
  dateCreation: Date;
  dateIncident?: Date | null;
  interlocuteurNom?: string;
  interlocuteurCode?: string;
  interlocuteurDepartement?: string;
  autoGenerated: boolean;
  messagesCount: number;
  [key: string]: any;
}

interface Props {
  memos: Memo[];
  isLoading?: boolean;
  error?: string;
  emptyTitle?: string;
  emptyDescription?: string;
  onRetry?: () => void;
}

const props = withDefaults(defineProps<Props>(), {
  isLoading: false,
  error: '',
  emptyTitle: 'Aucun mémo trouvé',
  emptyDescription: 'Aucun mémo ne correspond à vos critères',
  onRetry: undefined,
});

const emit = defineEmits<{
  'memo-click': [memo: Memo];
}>();

// ── State ──────────────────────────────────────
const currentPage = ref(1);
const perPage = ref(10);

// ── Pagination ─────────────────────────────────
const totalPages = computed(() => Math.max(1, Math.ceil(props.memos.length / perPage.value)));

// Reset page quand perPage ou la liste change
watch([perPage, () => props.memos.length], () => { currentPage.value = 1; });

const memosPagines = computed(() => {
  const start = (currentPage.value - 1) * perPage.value;
  return props.memos.slice(start, start + perPage.value);
});

const paginationPages = computed(() => {
  const total = totalPages.value;
  const cur = currentPage.value;
  const pages: (number | '...')[] = [];

  if (total <= 7) {
    for (let i = 1; i <= total; i++) pages.push(i);
    return pages;
  }
  pages.push(1);
  if (cur > 3) pages.push('...');
  for (let i = Math.max(2, cur - 1); i <= Math.min(total - 1, cur + 1); i++) pages.push(i);
  if (cur < total - 2) pages.push('...');
  pages.push(total);
  return pages;
});

// ── Helpers ────────────────────────────────────
const handleMemoClick = (memo: Memo) => emit('memo-click', memo);

const initials = (name?: string): string => {
  if (!name) return '?';
  return name.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase();
};

const formatDate = (date: Date | string | null | undefined): string => {
  if (!date) return '—';
  return new Date(date).toLocaleDateString('fr-FR', {
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit'
  });
};

const getTypeIcon = (type: string): string => ({
  delay_justification: '⏱',
  absence_justification: '🏥',
  absence_notification: '📢',
  session_closure: '🔒',
  auto_generated: '🤖',
  correction_request: '✏️',
}[type] ?? '📝');

const getTypeLabel = (type: string): string => ({
  delay_justification: 'delay_justification',
  absence_justification: 'absence_justification',
  absence_notification: 'absence_notification',
  session_closure: 'session_closure',
  auto_generated: 'auto_generated',
  correction_request: 'correction_request',
}[type] ?? type);

const getStatusLabel = (status: string): string => ({
  pending: 'En attente',
  submitted: 'En attente',
  approved: 'Approuvé',
  rejected: 'Rejeté',
}[status] ?? status);

const typeIconBg = (type: string): string => ({
  delay_justification: 'bg-blue-50 text-blue-600',
  absence_justification: 'bg-yellow-50 text-yellow-600',
  session_closure: 'bg-red-50 text-red-600',
  auto_generated: 'bg-purple-50 text-purple-600',
  correction_request: 'bg-red-50 text-red-600',
  absence_notification: 'bg-orange-50 text-orange-600',
}[type] ?? 'bg-gray-50 text-gray-600');

const typeBadgeClass = (type: string): string => ({
  delay_justification: 'bg-blue-50 text-blue-700',
  absence_justification: 'bg-yellow-50 text-yellow-700',
  session_closure: 'bg-gray-100 text-gray-600',
  auto_generated: 'bg-purple-50 text-purple-700',
  correction_request: 'bg-red-50 text-red-700',
  absence_notification: 'bg-orange-50 text-orange-700',
}[type] ?? 'bg-gray-100 text-gray-600');

const statusBadgeClass = (status: string): string => ({
  pending: 'bg-orange-50 text-orange-600',
  submitted: 'bg-orange-50 text-orange-600',
  approved: 'bg-green-50 text-green-700',
  rejected: 'bg-red-50 text-red-600',
}[status] ?? 'bg-gray-100 text-gray-600');

const statusBorderColor = (status: string): string => ({
  pending: 'bg-orange-400',
  submitted: 'bg-orange-400',
  approved: 'bg-green-500',
  rejected: 'bg-red-400',
}[status] ?? 'bg-gray-300');
</script>