export type AttendanceStatus =
  | 'PRESENT'
  | 'LATE'
  | 'ABSENT'
  | 'REST_DAY'
  | 'UNDETERMINED'
  | 'PENDING';

export type ScheduleState = 'WORK_DAY' | 'REST_DAY' | 'UNRESOLVED';

export type ScheduleSource = 'DIRECT' | 'ROTATION' | 'DEFAULT' | 'EXCEPTION';

export type ScheduleResolutionIssue = 'MISSING_SCHEDULE' | 'INVALID_SCHEDULE';

export type AttendanceIssue =
  | 'PRESENCE_ON_REST_DAY'
  | 'PRESENCE_WITHOUT_SCHEDULE'
  | 'ACTIVITY_OUTSIDE_EXPECTED_BLOCK'
  | ScheduleResolutionIssue
  | 'OPEN_SESSION'
  | 'INCOMPLETE_SESSION'
  | 'MISSING_DURATION'
  | 'CORRECTED_PRESENCE';

/**
 * Date métier. La valeur reste une chaîne et n'est pas reconvertie en UTC.
 * Le service appelant doit fournir le format YYYY-MM-DD.
 */
export type BusinessDate = string;

/**
 * Heure métier au format HH:mm ou HH:mm:ss.
 * La classification travaille à la minute et ignore les secondes.
 */
export type BusinessTime = string;


export type PresenceEvidenceKind = 'DIRECT' | 'CORRECTED' | 'NONE';

export interface AttendancePresenceEvidence {
  kind: PresenceEvidenceKind;
  occurredAt: BusinessTime | null;
  occurredDate: BusinessDate | null;
  autoGenerated: boolean;
}

export type AttendanceExtraPolicy =
  | {
      resolved: true;
      allowed: false;
      maxMinutes: null;
    }
  | {
      resolved: true;
      allowed: true;
      maxMinutes: number;
    }
  | {
      resolved: false;
      allowed: null;
      maxMinutes: null;
    };

export interface ExpectedWorkBlock {
  startTime: BusinessTime;
  endTime: BusinessTime;
  toleranceMinutes: number;
  pauseStartTime?: BusinessTime | null;
  pauseEndTime?: BusinessTime | null;
}

export interface WorkDaySchedule {
  state: 'WORK_DAY';
  source: ScheduleSource;
  expectedBlocks: readonly ExpectedWorkBlock[];
  /** Politique E+ issue du SessionModel du template applicable. */
  extraPolicy?: AttendanceExtraPolicy;
}

export interface RestDaySchedule {
  state: 'REST_DAY';
  source: ScheduleSource;
  expectedBlocks: readonly [];
}

export interface UnresolvedSchedule {
  state: 'UNRESOLVED';
  source: ScheduleSource | null;
  expectedBlocks: readonly [];
  issue: ScheduleResolutionIssue;
}

export type AttendanceDaySchedule =
  | WorkDaySchedule
  | RestDaySchedule
  | UnresolvedSchedule;

/**
 * Activité déjà agrégée pour un seul couple employé × journée métier.
 * incompleteSessionCount exclut les sessions OPEN afin de ne pas les compter deux fois.
 */
export interface AttendanceActivityInterval {
  startDate: BusinessDate;
  startTime: BusinessTime;
  endDate: BusinessDate | null;
  endTime: BusinessTime | null;
  /**
   * Durée nette de ce segment que l'on peut attribuer sans ambiguïté à la
   * journée métier projetée. Null signifie que l'activité reste réelle et
   * visible, mais qu'elle ne doit pas alimenter E+/E- pour cette occurrence.
   */
  attributableNetMinutes?: number | null;
}

export interface AttendanceDayActivityInput {
  sessionCount: number;
  /** GUIDs des WorkSessions qui contribuent à cette journée métier. */
  sourceSessionGuids?: readonly string[];
  /** GUIDs des CLOCK_IN chargés pour ces sessions. */
  sourceClockInEntryGuids?: readonly string[];
  openSessionCount: number;
  incompleteSessionCount: number;
  firstClockIn: BusinessTime | null;
  firstClockInDate: BusinessDate | null;
  lastClockOut: BusinessTime | null;
  lastClockOutDate: BusinessDate | null;
  grossMinutes: number | null;
  pauseMinutes: number | null;
  /**
   * Preuve de présence issue des pointages. Nullable pour compatibilité avec
   * les anciens producteurs qui ne fournissaient que des WorkSessions.
   */
  presenceEvidence?: AttendancePresenceEvidence | null;
  /** Intervalles réels touchant la journée, y compris une session commencée la veille. */
  intervals?: readonly AttendanceActivityInterval[];
}

export interface AttendanceDayActivity extends AttendanceDayActivityInput {
  hasActivity: boolean;
  /**
   * Une présence peut être prouvée indépendamment de la complétude de la session.
   * En l'absence de presenceEvidence, le comportement historique est conservé.
   */
  hasPresence: boolean;
  presenceEvidence: AttendancePresenceEvidence | null;
  netMinutes: number | null;
}

export interface AttendanceDayResult {
  status: AttendanceStatus;
  /** Retard métier réel, après déduction de la tolérance du planning. */
  delayMinutes: number | null;
  /** Écart positif entre l'heure d'arrivée et l'heure théorique, avant tolérance. */
  arrivalDelayMinutes: number | null;
  toleranceMinutes: number | null;
  /** Durée nette attendue d'après les blocs du planning, pauses planifiées déduites. */
  expectedWorkMinutes: number | null;

  /**
   * Durée nette réellement attribuée à cette occurrence planifiée.
   * Elle peut différer de activity.netMinutes lorsque l'activité réelle couvre
   * plusieurs journées ou plusieurs occurrences.
   */
  attributedWorkMinutes: number | null;
  /** Écart signé de l'occurrence = attributedWorkMinutes - expectedWorkMinutes. */
  rawDeltaMinutes: number | null;
  /** Partie négative de l'écart, exprimée en valeur positive. */
  deficitMinutes: number | null;
  /** E+ retenu selon la politique du SessionModel. */
  creditedExtraMinutes: number | null;
  /** Surplus réel au-delà de la marge E+ autorisée. Il n'est jamais supprimé. */
  excessBeyondExtraMinutes: number | null;
  /** Politique E+ résolue pour cette occurrence. */
  extraAllowed: boolean | null;
  extraMaxMinutes: number | null;

  /**
   * Indique si cette journée entre dans le dénominateur
   * employee_working_days_expected.
   */
  rateEligible: boolean;
}

export interface AttendanceDay {
  employeeId: number;
  employeeGuid: string;
  date: BusinessDate;
  schedule: AttendanceDaySchedule;
  activity: AttendanceDayActivity;
  result: AttendanceDayResult;
  issues: AttendanceIssue[];
}

export interface CreateAttendanceDayInput {
  employeeId: number;
  employeeGuid: string;
  date: BusinessDate;
  schedule: AttendanceDaySchedule;
  activity: AttendanceDayActivityInput;

  /**
   * Doit être calculé dans le fuseau métier à partir de la fin du dernier
   * bloc attendu. La fonction de classification ne manipule aucun Date.
   */
  hasExpectedWorkDayEnded: boolean;
}
