import { defineStore } from 'pinia';
import { computed, ref } from 'vue';

import MemoService from '@/service/MemoService';
import MemoRealtimeService, { type MemoRealtimePayload } from '@/service/MemoRealtimeService';

export interface MemoContent {
    message: Array<{ type: string; content: string }>;
    type: 'initial' | 'response' | 'validation';
    created_at: string;
    user: string;
}

export interface MemoEmployee {
    guid: string;
    tenant: string;
    email: string;
    first_name: string;
    last_name: string;
    phone_number: string;
    country: string;
    employee_code: string;
    avatar_url: string | null;
    hire_date: string;
    department: string;
    job_title: string;
    active: boolean;
    last_login_at: string;
}

export interface ApiMemo {
    guid: string;
    title: string;
    memo_type: string;
    memo_status: string;
    created_at: string;
    updated_at: string;
    incident_date_time?: string | null;
    incident_datetime?: string | null;
    author_user: MemoEmployee;
    target_user: MemoEmployee;
    validator_user?: MemoEmployee | null;
    auto_generated: boolean;
    messages_count: number;
    affected_entries: any[];
    memo_content: MemoContent[];
    latest_message?: MemoContent;
}

export interface Memo {
    guid: string;
    titre: string;
    contenu: string;
    type: string;
    statut: string;
    dateCreation: Date;
    dateModification: Date;
    dateIncident?: Date | null;
    createurId: string;
    createurNom: string;
    createurCode: string;
    createurDepartement: string;
    destinataireId: string;
    destinataireNom: string;
    destinataireCode: string;
    destinataireDepartement: string;
    autoGenerated: boolean;
    messagesCount: number;
    entriesAffectees: any[];
    memoContent?: MemoContent[];
}

export const useMemoStore = defineStore(
    'memo',
    () => {
        const memos = ref<Memo[]>([]);
        const employees = ref<MemoEmployee[]>([]);
        const rawData = ref<any>(null);
        const lastFetch = ref<number | null>(null);
        const isLoading = ref(false);
        const isRealtimeConnected = ref(false);

        const CACHE_DURATION = 60 * 1000;
        const READ_GUIDS_KEY = 'memo-read-guids';

        let _loadPromise: Promise<Memo[]> | null = null;
        const _refreshPromises = new Map<string, Promise<Memo | null>>();
        const _lastMemoRefreshAt = new Map<string, number>();
        let _realtimeManagerGuid: string | null = null;

        const _loadReadGuids = (): Set<string> => {
            try {
                const raw = localStorage.getItem(READ_GUIDS_KEY);
                const parsed = raw ? JSON.parse(raw) : [];
                return new Set(Array.isArray(parsed) ? parsed : []);
            } catch {
                return new Set();
            }
        };

        const _saveReadGuids = (set: Set<string>) => {
            try {
                localStorage.setItem(READ_GUIDS_KEY, JSON.stringify([...set]));
            } catch {
                // localStorage indisponible : le badge reste uniquement en mémoire.
            }
        };

        const _readGuids = ref<Set<string>>(_loadReadGuids());

        const unreadMemosCount = computed(
            () => memos.value.filter((memo) => !_readGuids.value.has(memo.guid)).length,
        );
        const hasUnreadMemos = computed(() => unreadMemosCount.value > 0);
        const totalMemos = computed(() => memos.value.length);

        const isCacheValid = computed(() => {
            if (!lastFetch.value) return false;
            return Date.now() - lastFetch.value < CACHE_DURATION;
        });

        const memosByType = computed(() => {
            const grouped: Record<string, Memo[]> = {};
            memos.value.forEach((memo) => {
                if (!grouped[memo.type]) grouped[memo.type] = [];
                grouped[memo.type].push(memo);
            });
            return grouped;
        });

        const memosByStatus = computed(() => {
            const grouped: Record<string, Memo[]> = {};
            memos.value.forEach((memo) => {
                if (!grouped[memo.statut]) grouped[memo.statut] = [];
                grouped[memo.statut].push(memo);
            });
            return grouped;
        });

        const extraireContenuTexte = (memoContent: MemoContent[] = []): string => {
            if (!memoContent.length) return 'Aucun contenu';

            const textes: string[] = [];
            memoContent.forEach((content) => {
                if (!Array.isArray(content.message)) return;
                content.message.forEach((msg) => {
                    if (msg.type === 'text' && msg.content) {
                        textes.push(msg.content);
                    } else if (msg.type === 'link' && msg.content) {
                        textes.push(
                            msg.content.match(/\.(m4a|mp3|wav|ogg|webm)$/i)
                                ? '🎤 Message vocal'
                                : `🔗 ${msg.content}`,
                        );
                    }
                });
            });

            return textes.length ? textes.join(' • ') : 'Aucun contenu';
        };

        const transformApiMemo = (memoApi: ApiMemo): Memo => {
            const auteur = memoApi.author_user;
            const destinataire = memoApi.target_user;
            const incident = memoApi.incident_date_time ?? memoApi.incident_datetime ?? null;

            return {
                guid: memoApi.guid,
                titre: memoApi.title || 'Sans titre',
                contenu: extraireContenuTexte(memoApi.memo_content),
                type: memoApi.memo_type,
                statut: memoApi.memo_status,
                dateCreation: new Date(memoApi.created_at),
                dateModification: new Date(memoApi.updated_at),
                dateIncident: incident ? new Date(incident) : null,
                createurId: auteur?.guid || '',
                createurNom: auteur ? `${auteur.first_name} ${auteur.last_name}` : 'Inconnu',
                createurCode: auteur?.employee_code || 'N/A',
                createurDepartement: auteur?.department || 'N/A',
                destinataireId: destinataire?.guid || '',
                destinataireNom: destinataire
                    ? `${destinataire.first_name} ${destinataire.last_name}`
                    : 'N/A',
                destinataireCode: destinataire?.employee_code || 'N/A',
                destinataireDepartement: destinataire?.department || 'N/A',
                autoGenerated: memoApi.auto_generated,
                messagesCount: memoApi.messages_count,
                entriesAffectees: memoApi.affected_entries || [],
                memoContent: memoApi.memo_content,
            };
        };

        const _rebuildEmployees = (items: ApiMemo[]): void => {
            const map = new Map<string, MemoEmployee>();
            items.forEach((memo) => {
                if (memo.author_user?.guid) map.set(memo.author_user.guid, memo.author_user);
                if (memo.target_user?.guid) map.set(memo.target_user.guid, memo.target_user);
                if (memo.validator_user?.guid) map.set(memo.validator_user.guid, memo.validator_user);
            });
            employees.value = Array.from(map.values());
        };

        const _extractListItems = (response: any): ApiMemo[] => {
            const memosData = response?.data?.data?.memos ?? response?.data?.memos ?? response?.data?.data ?? response?.memos;
            return Array.isArray(memosData?.items) ? memosData.items : [];
        };

        const _extractSingleMemo = (response: any): ApiMemo | null => {
            return (
                response?.data?.data?.memo ??
                response?.data?.memo ??
                response?.data?.data ??
                response?.memo ??
                null
            );
        };

        const _upsertApiMemo = (memoApi: ApiMemo): Memo => {
            const transformed = transformApiMemo(memoApi);
            const index = memos.value.findIndex((memo) => memo.guid === transformed.guid);

            if (index >= 0) memos.value.splice(index, 1, transformed);
            else memos.value.unshift(transformed);

            const employeeMap = new Map(employees.value.map((employee) => [employee.guid, employee]));
            if (memoApi.author_user?.guid) employeeMap.set(memoApi.author_user.guid, memoApi.author_user);
            if (memoApi.target_user?.guid) employeeMap.set(memoApi.target_user.guid, memoApi.target_user);
            if (memoApi.validator_user?.guid) employeeMap.set(memoApi.validator_user.guid, memoApi.validator_user);
            employees.value = Array.from(employeeMap.values());

            return transformed;
        };

        const loadMemos = async (managerGuid: string, forceRefresh = false): Promise<Memo[]> => {
            if (isCacheValid.value && !forceRefresh) return memos.value;
            if (_loadPromise) return _loadPromise;

            _loadPromise = (async () => {
                try {
                    isLoading.value = true;
                    const response = await MemoService.listMemo(managerGuid);
                    const items = _extractListItems(response);

                    _rebuildEmployees(items);
                    memos.value = items.map(transformApiMemo);
                    rawData.value = response?.data ?? response;
                    lastFetch.value = Date.now();

                    return memos.value;
                } finally {
                    isLoading.value = false;
                    _loadPromise = null;
                }
            })();

            return _loadPromise;
        };

        const getMemoByGuid = (guid: string): Memo | undefined =>
            memos.value.find((memo) => memo.guid === guid);

        const getMemosByEmployee = (employeeGuid: string): Memo[] =>
            memos.value.filter(
                (memo) => memo.createurId === employeeGuid || memo.destinataireId === employeeGuid,
            );

        const getMemosByType = (type: string): Memo[] =>
            memos.value.filter((memo) => memo.type === type);

        const getMemosByStatus = (status: string): Memo[] =>
            memos.value.filter((memo) => memo.statut === status);

        const getEmployeeByGuid = (guid: string): MemoEmployee | undefined =>
            employees.value.find((employee) => employee.guid === guid);

        const markMemoAsRead = (memoGuid: string) => {
            _readGuids.value.add(memoGuid);
            _saveReadGuids(_readGuids.value);
            _readGuids.value = new Set(_readGuids.value);
        };

        const markAllMemosAsRead = () => {
            memos.value.forEach((memo) => _readGuids.value.add(memo.guid));
            _saveReadGuids(_readGuids.value);
            _readGuids.value = new Set(_readGuids.value);
        };

        const clearCache = () => {
            memos.value = [];
            employees.value = [];
            rawData.value = null;
            lastFetch.value = null;
        };

        /** Rafraîchit uniquement le mémo concerné, jamais toute la collection. */
        const refreshMemo = async (_managerGuid: string, memoGuid: string): Promise<Memo | null> => {
            const existing = _refreshPromises.get(memoGuid);
            if (existing) return existing;

            // Un événement Socket et le callback local de la même action peuvent arriver presque
            // simultanément. Cette petite fenêtre évite un deuxième GET identique.
            const lastRefreshAt = _lastMemoRefreshAt.get(memoGuid) || 0;
            const cachedMemo = getMemoByGuid(memoGuid);
            if (cachedMemo && Date.now() - lastRefreshAt < 1000) return cachedMemo;

            const promise = (async () => {
                try {
                    const response = await MemoService.getMemoByGuid(memoGuid);
                    const memoApi = _extractSingleMemo(response);
                    if (!memoApi?.guid) return null;
                    const updated = _upsertApiMemo(memoApi);
                    _lastMemoRefreshAt.set(memoGuid, Date.now());
                    return updated;
                } catch (error: any) {
                    // Si le mémo vient d'être supprimé, le retirer localement.
                    if (error?.response?.status === 404) {
                        removeMemo(memoGuid);
                        return null;
                    }
                    throw error;
                } finally {
                    _refreshPromises.delete(memoGuid);
                }
            })();

            _refreshPromises.set(memoGuid, promise);
            return promise;
        };

        const removeMemo = (memoGuid: string): void => {
            memos.value = memos.value.filter((memo) => memo.guid !== memoGuid);
        };

        const _handleRealtimeChange = async (
            managerGuid: string,
            payload: MemoRealtimePayload,
        ): Promise<void> => {
            if (!payload?.guid) return;
            if (!payload.affectedUserGuids?.includes(managerGuid)) return;

            if (payload.action === 'deleted') {
                removeMemo(payload.guid);
                return;
            }

            await refreshMemo(managerGuid, payload.guid);

            // Une action réalisée par le manager lui-même ne doit pas créer un faux "non lu".
            if (payload.actorUserGuid === managerGuid) {
                markMemoAsRead(payload.guid);
            }
        };

        const startRealtime = async (managerGuid: string): Promise<void> => {
            if (!managerGuid) return;

            if (_realtimeManagerGuid && _realtimeManagerGuid !== managerGuid) {
                MemoRealtimeService.disconnect();
            }
            _realtimeManagerGuid = managerGuid;

            // Une synchronisation initiale uniquement si le cache n'est pas exploitable.
            await loadMemos(managerGuid);

            await MemoRealtimeService.connect(managerGuid, {
                onChange: (payload) => _handleRealtimeChange(managerGuid, payload),
                onReconnect: async () => {
                    // Rattrape les éventuels événements perdus pendant la coupure réseau.
                    await loadMemos(managerGuid, true);
                },
                onConnectionChange: (connected) => {
                    isRealtimeConnected.value = connected;
                },
            });
        };

        const stopRealtime = (): void => {
            MemoRealtimeService.disconnect();
            _realtimeManagerGuid = null;
            isRealtimeConnected.value = false;
        };

        // Compatibilité temporaire avec un Header qui appelle encore startPolling/stopPolling.
        // Ces méthodes NE font plus aucun polling : elles délèguent au temps réel Socket.IO.
        const startPolling = (managerGuid: string) => startRealtime(managerGuid);
        const stopPolling = () => stopRealtime();

        return {
            memos,
            employees,
            rawData,
            isLoading,
            lastFetch,
            isRealtimeConnected,
            totalMemos,
            isCacheValid,
            memosByType,
            memosByStatus,
            unreadMemosCount,
            hasUnreadMemos,
            loadMemos,
            getMemoByGuid,
            getMemosByEmployee,
            getMemosByType,
            getMemosByStatus,
            getEmployeeByGuid,
            clearCache,
            refreshMemo,
            removeMemo,
            markMemoAsRead,
            markAllMemosAsRead,
            startRealtime,
            stopRealtime,
            startPolling,
            stopPolling,
        };
    },
    {
        persist: {
            key: 'memo-store',
            storage: localStorage,
            paths: ['memos', 'employees', 'rawData', 'lastFetch'],
        },
    } as any,
);