import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

import MemoService from '@/service/MemoService'

// 📝 Types pour les mémos
export interface MemoContent {
  message: Array<{ type: string; content: string }>
  type: 'initial' | 'response' | 'validation'
  created_at: string
  user: string
}

export interface MemoEmployee {
  guid: string
  tenant: string
  email: string
  first_name: string
  last_name: string
  phone_number: string
  country: string
  employee_code: string
  avatar_url: string | null
  hire_date: string
  department: string
  job_title: string
  active: boolean
  last_login_at: string
}

export interface ApiMemo {
  guid: string
  title: string
  memo_type: string
  memo_status: string
  created_at: string
  updated_at: string
  incident_date_time: string | null
  author_user: MemoEmployee
  target_user: MemoEmployee
  auto_generated: boolean
  messages_count: number
  affected_entries: any[]
  memo_content: MemoContent[]
  latest_message?: MemoContent
}

export interface Memo {
  guid: string
  titre: string
  contenu: string
  type: string
  statut: string
  dateCreation: Date
  dateModification: Date
  dateIncident?: Date | null
  createurId: string
  createurNom: string
  createurCode: string
  createurDepartement: string
  destinataireId: string
  destinataireNom: string
  destinataireCode: string
  destinataireDepartement: string
  autoGenerated: boolean
  messagesCount: number
  entriesAffectees: any[]
  memoContent?: MemoContent[]
}

export const useMemoStore = defineStore('memo', () => {
  // 📦 État
  const memos = ref<Memo[]>([])
  const employees = ref<MemoEmployee[]>([])
  const rawData = ref<any>(null)
  const lastFetch = ref<number | null>(null)
  const isLoading = ref(false)
  const CACHE_DURATION = 60 * 1000 // 24 heures
  // const CACHE_DURATION = 24 * 60 * 60 * 1000 // 24 heures

  // 📊 Computed
  const totalMemos = computed(() => memos.value.length)

  const isCacheValid = computed(() => {
    if (!lastFetch.value) return false
    return Date.now() - lastFetch.value < CACHE_DURATION
  })

  // Mémos par type
  const memosByType = computed(() => {
    const grouped: { [key: string]: Memo[] } = {}
    memos.value.forEach(memo => {
      if (!grouped[memo.type]) {
        grouped[memo.type] = []
      }
      grouped[memo.type].push(memo)
    })
    return grouped
  })

  // Mémos par statut
  const memosByStatus = computed(() => {
    const grouped: { [key: string]: Memo[] } = {}
    memos.value.forEach(memo => {
      if (!grouped[memo.statut]) {
        grouped[memo.statut] = []
      }
      grouped[memo.statut].push(memo)
    })
    return grouped
  })

  // 🔧 Helper Functions
  const extraireContenuTexte = (memoContent: MemoContent[]): string => {
    if (!memoContent || memoContent.length === 0) {
      return 'Aucun contenu'
    }

    const textes: string[] = []
    let hasVoiceMessage = false

    memoContent.forEach(content => {
      if (content.message && Array.isArray(content.message)) {
        content.message.forEach(msg => {
          if (msg.type === 'text' && msg.content) {
            textes.push(msg.content)
          } else if (msg.type === 'link' && msg.content) {
            if (msg.content.match(/\.(m4a|mp3|wav|ogg|webm)$/i)) {
              hasVoiceMessage = true
              textes.push('🎤 Message vocal')
            } else {
              textes.push(`🔗 ${msg.content}`)
            }
          }
        })
      }
    })

    if (textes.length === 0 && hasVoiceMessage) {
      return '🎤 Message vocal uniquement'
    }

    return textes.length > 0 ? textes.join(' • ') : 'Aucun contenu'
  }

  const transformApiMemo = (memoApi: ApiMemo): Memo => {
    const auteur = memoApi.author_user
    const destinataire = memoApi.target_user

    return {
      guid: memoApi.guid,
      titre: memoApi.title || 'Sans titre',
      contenu: extraireContenuTexte(memoApi.memo_content),
      type: memoApi.memo_type,
      statut: memoApi.memo_status,
      dateCreation: new Date(memoApi.created_at),
      dateModification: new Date(memoApi.updated_at),
      dateIncident: memoApi.incident_date_time ? new Date(memoApi.incident_date_time) : null,
      createurId: auteur?.guid || '',
      createurNom: auteur ? `${auteur.first_name} ${auteur.last_name}` : 'Inconnu',
      createurCode: auteur?.employee_code || 'N/A',
      createurDepartement: auteur?.department || 'N/A',
      destinataireId: destinataire?.guid || '',
      destinataireNom: destinataire ? `${destinataire.first_name} ${destinataire.last_name}` : 'N/A',
      destinataireCode: destinataire?.employee_code || 'N/A',
      destinataireDepartement: destinataire?.department || 'N/A',
      autoGenerated: memoApi.auto_generated,
      messagesCount: memoApi.messages_count,
      entriesAffectees: memoApi.affected_entries || [],
      memoContent: memoApi.memo_content
    }
  }

  // 🔄 Actions
  const loadMemos = async (managerGuid: string, forceRefresh = false) => {
    // Si cache valide et pas de force refresh, ne rien faire
    if (isCacheValid.value && !forceRefresh) {
      console.log('✅ Utilisation du cache mémos')
      return memos.value
    }

    try {
      isLoading.value = true
      console.log('🔄 Chargement des mémos depuis l\'API...')

      const response = await MemoService.listMemo(managerGuid)

      let memosData: any = null

      if (response?.data?.data?.memos) {
        memosData = response.data.data.memos
      } else if (response?.data?.memos) {
        memosData = response.data.memos
      }

      if (memosData && memosData.items && Array.isArray(memosData.items)) {
        // Collecter tous les employés uniques
        const employesMap = new Map<string, MemoEmployee>()

        memosData.items.forEach((memoApi: ApiMemo) => {
          // Ajouter l'auteur
          if (memoApi.author_user) {
            employesMap.set(memoApi.author_user.guid, memoApi.author_user)
          }

          // Ajouter le destinataire
          if (memoApi.target_user) {
            employesMap.set(memoApi.target_user.guid, memoApi.target_user)
          }
        })

        employees.value = Array.from(employesMap.values())

        // Transformer les mémos
        memos.value = memosData.items.map((memoApi: ApiMemo) => transformApiMemo(memoApi))

        rawData.value = response.data
        lastFetch.value = Date.now()

        console.log(`✅ ${memos.value.length} mémo(s) chargé(s)`)
        console.log(`👥 ${employees.value.length} employé(s) trouvé(s)`)

        return memos.value
      } else {
        console.error('❌ Structure de données invalide')
        memos.value = []
        employees.value = []
        return []
      }
    } catch (error) {
      console.error('❌ Erreur chargement mémos:', error)
      throw error
    } finally {
      isLoading.value = false
    }
  }

  const getMemoByGuid = (guid: string): Memo | undefined => {
    return memos.value.find(memo => memo.guid === guid)
  }

  const getMemosByEmployee = (employeeGuid: string): Memo[] => {
    return memos.value.filter(
      memo => memo.createurId === employeeGuid || memo.destinataireId === employeeGuid
    )
  }

  const getMemosByType = (type: string): Memo[] => {
    return memos.value.filter(memo => memo.type === type)
  }

  const getMemosByStatus = (status: string): Memo[] => {
    return memos.value.filter(memo => memo.statut === status)
  }

  const getEmployeeByGuid = (guid: string): MemoEmployee | undefined => {
    return employees.value.find(emp => emp.guid === guid)
  }

  const clearCache = () => {
    memos.value = []
    employees.value = []
    rawData.value = null
    lastFetch.value = null
  }

  // Rafraîchir un mémo spécifique après modification
  const refreshMemo = async (managerGuid: string, memoGuid: string) => {
    try {
      console.log(`🔄 Rafraîchissement du mémo ${memoGuid}...`)

      // Forcer le rechargement complet des mémos
      await loadMemos(managerGuid, true)

      // Récupérer le mémo mis à jour
      const updatedMemo = getMemoByGuid(memoGuid)

      if (updatedMemo) {
        console.log('✅ Mémo rafraîchi avec succès')
        return updatedMemo
      }

      console.log('⚠️ Mémo non trouvé après rafraîchissement')
      return null
    } catch (error) {
      console.error('❌ Erreur rafraîchissement mémo:', error)
      throw error
    }
  }


  return {
    // State
    memos,
    employees,
    rawData,
    isLoading,
    lastFetch,

    // Computed
    totalMemos,
    isCacheValid,
    memosByType,
    memosByStatus,

    // Actions
    loadMemos,
    getMemoByGuid,
    getMemosByEmployee,
    getMemosByType,
    getMemosByStatus,
    getEmployeeByGuid,
    clearCache,
    refreshMemo
  }
}, {
  persist: {
    key: 'memo-store',
    storage: localStorage,
    paths: ['memos', 'employees', 'rawData', 'lastFetch']
  }
} as any)