export const PLANNING_SOLVER_MAX_SECONDS = 30 * 60;

export const PLANNING_SOLVER_HTTP_GRACE_SECONDS = 60;

export const PLANNING_SOLVER_HTTP_TIMEOUT_MS =
  (PLANNING_SOLVER_MAX_SECONDS + PLANNING_SOLVER_HTTP_GRACE_SECONDS) * 1000;
